name    'alkivi-fail2ban'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-fail2ban'
author 'alkivi'
license 'LGPLv3'
summary 'Controls fail2ban server and rules'
description 'Setup fail2ban and handle rules configuration in puppet'
project_page 'https://github.com/alkivi-sas/puppet-fail2ban'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/concat', '1.0.0'
